%% mmc5983ma calibration results

fname = which( 'mag-cal-0xca.csv');
tsc = flatball_log_proc( fname);

%% calibrate magnetometer (use as necessary)
D = [tsc.mag_x.Data, tsc.mag_y.Data, tsc.mag_z.Data];
D( D >= 500) = 0;
D( D <= -500) = 0;
[A,b,expmfs] = magcal( D);
C = (D-b)*A; % calibrated data

t = tsc.Time;
ts = timeseries( C(:,1), t, 'Name', 'mag_x_cal');
tsc = tsc.addts( ts);
ts = timeseries( C(:,2), t, 'Name', 'mag_y_cal');
tsc = tsc.addts( ts);
ts = timeseries( C(:,3), t, 'Name', 'mag_z_cal');
tsc = tsc.addts( ts);

%%
mag_cal_plots;
title( 'mmc5983ma xyz magnetometer calibration');

% D = [tsc.mag_x.Data, tsc.mag_y.Data, tsc.mag_z.Data];
% [A,b,expmfs] = magcal( D);
% C = (D-b)*A; % calibrated data

A
b
expmfs

%%
% new_formatted_fig( 'mag-3d-calibration');
% plot3( tsc.mag_x.Data, tsc.mag_y.Data, tsc.mag_z.Data, '.');
% hold all;
% plot3( tsc.mag_x_cal.Data, tsc.mag_y_cal.Data, tsc.mag_z_cal.Data, '.');
% hold off;
% grid on;
% xlim([-1 1] .* 100); xlabel( 'uT');
% ylim([-1 1] .* 100); ylabel( 'uT');
% zlim([-1 1] .* 100); zlabel( 'uT');
% legend( {'uncalibrated', 'calibrated'}, 'Location','best');

%% legacy attempt using magneto and a txt file generated by custom sketch

% mag_norm = 8.0; % (G)
% 
% mag_cal_b = [-1.208058 -0.685526 -1.448126];
% mag_cal_A_inv = zeros(3,3);
% 
% mag_cal_A_inv(1,1) = 6.612380;
% mag_cal_A_inv(1,2) = -1.799944;
% mag_cal_A_inv(1,3) = -1.825606;
% mag_cal_A_inv(2,1) = mag_cal_A_inv(1,2);
% mag_cal_A_inv(2,2) = 6.364024;
% mag_cal_A_inv(2,3) = -1.553497;
% mag_cal_A_inv(3,1) = mag_cal_A_inv(1,3);
% mag_cal_A_inv(3,2) = mag_cal_A_inv(2,3);
% mag_cal_A_inv(3,3) = 6.300003;
% 
% mag_cal_A_slf_chk = mag_cal_A_inv;
% mag_cal_A_slf_chk(1,1) = 0.190955;
% mag_cal_A_slf_chk(1,2) = 0.071840;
% mag_cal_A_slf_chk(1,3) = 0.073049;
% mag_cal_A_slf_chk(2,1) = mag_cal_A_slf_chk(1,2);
% mag_cal_A_slf_chk(2,2) = 0.194225;
% mag_cal_A_slf_chk(2,3) = 0.068711;
% mag_cal_A_slf_chk(3,1) = mag_cal_A_slf_chk(1,3);
% mag_cal_A_slf_chk(3,2) = mag_cal_A_slf_chk(2,3);
% mag_cal_A_slf_chk(3,3) = 0.196841;
% 
% %% calculations
% mag_cal_A = mag_cal_A_inv ^ -1;
% 
% %% results
% fprintf( 'mmc5983ma calibration results\n');
% fprintf( '--> A ^ -1 - magneto v1p2\n');
% disp( mag_cal_A_inv);
% fprintf( '--> A - magneto v1p2 self check\n');
% disp( mag_cal_A_slf_chk);
% fprintf( '--> A - inverse of magneto v1p2 A ^ -1\n');
% disp( mag_cal_A);
% fprintf( '--> b\n');
% disp( mag_cal_b);
% disp( 'h-cal = A^-1 * (h-b)');